# Generated by Django 5.2.1 on 2025-05-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcode',
            name='qr_code_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
