# Generated by Django 5.2.1 on 2025-05-26 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_productcode_qr_code_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcode',
            name='date_expired',
            field=models.DateField(default=datetime.date(2025, 5, 26)),
        ),
        migrations.AddField(
            model_name='productcode',
            name='date_produced',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
        migrations.AddField(
            model_name='productcode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='productcode',
            name='ingredients',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='productcode',
            name='location_manufactured',
            field=models.CharField(default='Lagos', max_length=255),
        ),
        migrations.AddField(
            model_name='productcode',
            name='nafdac_no',
            field=models.CharField(default=101, max_length=50),
        ),
        migrations.AlterField(
            model_name='productcode',
            name='manufacturer',
            field=models.CharField(max_length=255),
        ),
    ]
