# Generated by Django 5.2.1 on 2025-09-12 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_productcode_date_expired_productcode_date_produced_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productcode',
            name='nafdac_no',
            field=models.CharField(default='101', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcode',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
