# Generated by Django 5.2.1 on 2025-11-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_productcode_user_alter_productcode_nafdac_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcode',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
